import gradio as gr 

def bot(user): 
 user = user.lower()
 answers = {
    "hi": "hello",
    "hello": "hi there",
    "hey": "hello",
    "good morning": "good morning",
    "good afternoon": "good afternoon",
    "good evening": "good evening",
    "how are you": "i am doing well",
    "what is your name": "i am a chatbot",
    "who made you": "a programmer made me",
    "what can you do": "i can answer simple questions",
    "how old are you": "i do not have an age",
    "where are you from": "i live inside a computer",
    "are you real": "i am a virtual assistant",
    "are you a robot": "you can think of me as one",
    "do you sleep": "no i do not sleep",
    "do you eat": "no i do not eat",
    "do you like music": "yes music is interesting",
    "what is python": "python is a programming language",
    "what is coding": "coding is writing instructions for computers",
    "what is a computer": "a computer processes information",
    "what is ai": "ai stands for artificial intelligence",
    "what is machine learning": "it is a way for computers to learn from data",
    "what is a variable": "a variable stores data",
    "what is a function": "a function performs a task",
    "what is a loop": "a loop repeats code",
    "what is a list": "a list stores multiple items",
    "what is a dictionary": "a dictionary stores key value pairs",
    "what is a string": "a string is text",
    "what is an integer": "an integer is a whole number",
    "what is a float": "a float is a decimal number",
    "what is a boolean": "a boolean is true or false",
    "what is your favorite color": "i like blue",
    "what is your favorite food": "i do not eat food",
    "what is your favorite animal": "i like cats",
    "what is your favorite movie": "i like science fiction movies",
    "what is your favorite game": "i enjoy strategy games",
    "what day is it": "i am not sure",
    "what time is it": "i cannot check the time",
    "tell me a joke": "why did the computer sneeze it had a virus",
    "tell me something interesting": "octopuses have three hearts",
    "what is the capital of france": "paris",
    "what is the capital of india": "new delhi",
    "what is the capital of japan": "tokyo",
    "what is the capital of germany": "berlin",
    "what is the capital of italy": "rome",
    "what is the capital of canada": "ottawa",
    "what is the capital of australia": "canberra",
    "what is 2 plus 2": "4",
    "what is 5 times 5": "25",
    "what is 10 divided by 2": "5",
    "what is the largest planet": "jupiter",
    "what planet do we live on": "earth",
    "how many days are in a week": "7",
    "how many months are in a year": "12",
    "how many hours are in a day": "24",
    "how many minutes are in an hour": "60",
    "how many seconds are in a minute": "60",
    "what is water": "water is h2o",
    "what is the sun": "the sun is a star",
    "what is the moon": "the moon is earths natural satellite",
    "what is gravity": "gravity pulls objects together",
    "what is electricity": "electricity is the flow of electric charge",
    "what is an atom": "an atom is the basic unit of matter",
    "what is a planet": "a planet orbits a star",
    "what is a galaxy": "a galaxy is a collection of stars",
    "what is the internet": "the internet connects computers worldwide",
    "what is a website": "a website is a collection of web pages",
    "what is html": "html structures web pages",
    "what is css": "css styles web pages",
    "what is javascript": "javascript adds interactivity to web pages",
    "what is gradio": "gradio helps build web interfaces",
    "what is github": "github hosts code repositories",
    "what is linux": "linux is an operating system",
    "what is windows": "windows is an operating system",
    "what is a file": "a file stores information",
    "what is a folder": "a folder stores files",
    "what is memory": "memory stores data for programs",
    "what is a cpu": "a cpu executes instructions",
    "what is a gpu": "a gpu processes graphics and parallel tasks",
    "what is ram": "ram is temporary memory",
    "what is storage": "storage keeps data long term",
    "what is a keyboard": "a keyboard is an input device",
    "what is a mouse": "a mouse is an input device",
    "what is a monitor": "a monitor displays information",
    "what is a printer": "a printer creates paper copies",
    "what is a network": "a network connects devices",
    "what is wifi": "wifi provides wireless networking",
    "what is bluetooth": "bluetooth connects nearby devices",
    "what is cybersecurity": "cybersecurity protects systems",
    "what is encryption": "encryption protects data",
    "what is a password": "a password helps secure accounts",
    "what is an app": "an app is a software application",
    "what is a browser": "a browser accesses websites",
    "what is google": "google is a search engine",
    "what is youtube": "youtube is a video platform",
    "what is an email": "email is electronic mail",
    "can you help me": "i can try",
    "can you code": "yes i can help with coding",
    "can you learn": "not in this simple version",
    "can you think": "i follow programmed rules",
    "can you count": "yes i can count",
    "can you sing": "i cannot sing",
    "can you dance": "i cannot dance",
    "do you like programming": "yes programming is interesting",
    "do you like games": "yes games are fun",
    "do you like science": "yes science is fascinating",
    "do you like math": "yes math is useful",
    "thank you": "you are welcome",
    "thanks": "no problem",
    "bye": "goodbye",
    "goodbye": "see you later",
    "see you later": "goodbye"
}

 if user in answers:
  return f"bot:{answers[user]}"
 else:
  return "bot dosent know"
app = gr.Interface(
    fn = bot,
   inputs = gr.Textbox(label = "Enter a Question"),
   outputs = gr.Textbox(label = "Chatbot")

)

app.launch(server_port=8000,server_name="127.0.0.1",share=False)
